kind: DaemonSet
apiVersion: apps/v1
metadata:
  labels:
    app: volume-provisioner
  name: {{ .Values.volumeProvisoner.name | default "volume-provisioner" }}
  namespace: {{ .Values.namespace | default "erda-system" }}
spec:
  selector:
    matchLabels:
      app: volume-provisioner
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: {{ .Values.volumeProvisoner.name | default "volume-provisioner" }}
      labels:
        app: volume-provisioner
    spec:
      serviceAccountName: volume-provisioner
      containers:
        - image: {{ .Values.image.repository }}/{{ .Values.volumeProvisoner.name | default "volume-provisioner" }}:{{ .Values.volumeProvisoner.version }}
          env:
            - name: PROVISIONER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOCAL_PROVISIONER_NAME
              value: dice/local-volume
            - name: NET_PROVISIONER_NAME
              value: dice/netdata-volume
          imagePullPolicy: Always
          name: volume-provisioner
          volumeMounts:
            - name: host-dir
              mountPath: /hostfs
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: host-dir
          hostPath:
            path: /
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      tolerations:
      - operator: Exists


